---

name: Executer un script python
on:
  - workflow_dispatch
  - push
#  issues:
#    type: [opened]

jobs:
  mon-test:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout code python
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          vache.py
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: pip install black flake8    
    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        black: true
        flake8: true
